# Generated by Django 5.0.6 on 2024-06-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="legsettings",
            name="on_sl",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ReExecuteLeg", "ReExecuteLeg"),
                    ("ReEnterLeg", "ReEnterLeg"),
                    ("KeepLegRunning", "KeepLegRunning"),
                    ("partial", "partial"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="legsettings",
            name="on_tp",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ReExecuteLeg", "ReExecuteLeg"),
                    ("ReEnterLeg", "ReEnterLeg"),
                    ("KeepLegRunning", "KeepLegRunning"),
                    ("partial", "partial"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="stop_loss",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
