# Generated by Django 5.0.6 on 2024-06-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_legsettings_on_sl_legsettings_on_tp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legsettings",
            name="on_sl",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ReExecuteLeg", "ReExecuteLeg"),
                    ("ReEnterLeg", "ReEnterLeg"),
                    ("KeepLegRunning", "KeepLegRunning"),
                    (
                        'partial(ReExecute_At_Opposite_Leg_Ltp, oppo_leg="leg2")',
                        'partial(ReExecute_At_Opposite_Leg_Ltp, oppo_leg="leg2")',
                    ),
                    (
                        'partial(SqOff_Legs, sqoff_legs=["leg3","leg4"])',
                        'partial(SqOff_Legs, sqoff_legs=["leg3","leg4"])',
                    ),
                    (
                        'partial(Execute_Legs, execute_legs=["leg4"])',
                        'partial(Execute_Legs, execute_legs=["leg4"])',
                    ),
                ],
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="legsettings",
            name="on_tp",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ReExecuteLeg", "ReExecuteLeg"),
                    ("ReEnterLeg", "ReEnterLeg"),
                    ("KeepLegRunning", "KeepLegRunning"),
                    (
                        'partial(Execute_Legs, execute_legs=["leg4","leg5"])',
                        'partial(Execute_Legs, execute_legs=["leg4","leg5"])',
                    ),
                ],
                max_length=150,
                null=True,
            ),
        ),
    ]
