# Generated by Django 5.0.6 on 2024-06-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_legsettings_on_sl_alter_legsettings_on_tp"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(max_length=255)),
                ("data", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="legsettings",
            name="on_sl",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ReExecuteLeg", "ReExecuteLeg"),
                    ("ReEnterLeg", "ReEnterLeg"),
                    ("KeepLegRunning", "KeepLegRunning"),
                    (
                        "partial_reexecute_opposite_leg",
                        "partial_reexecute_opposite_leg",
                    ),
                    ("partial_sqoff_legs", "partial_sqoff_legs"),
                    ("partial_execute_legs", "partial_execute_legs"),
                ],
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="legsettings",
            name="on_tp",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ReExecuteLeg", "ReExecuteLeg"),
                    ("ReEnterLeg", "ReEnterLeg"),
                    ("KeepLegRunning", "KeepLegRunning"),
                    ("partial_execute_legs", "partial_execute_legs"),
                ],
                max_length=150,
                null=True,
            ),
        ),
    ]
